if [ -z $1 ]
then
	param="${param}"
else
	param=$1
fi

cfg_folder="cfgs/${param}_200crops64"
rm -rf "${cfg_folder}/bs256"
mkdir "${cfg_folder}/bs256"
mv "${cfg_folder}/"*batchsize256* "${cfg_folder}/bs256" 
rm -rf "${cfg_folder}/bs128"
mkdir "${cfg_folder}/bs128"
mv "${cfg_folder}/"*batchsize128* "${cfg_folder}/bs128" 
rm -rf "${cfg_folder}/bs64"
mkdir "${cfg_folder}/bs64"
mv "${cfg_folder}/"*batchsize64* "${cfg_folder}/bs64"  
rm -rf "${cfg_folder}/bs32"
mkdir "${cfg_folder}/bs32"
mv "${cfg_folder}/"*batchsize32* "${cfg_folder}/bs32" 

cfg_folder="cfgs/${param}_100crops128"
rm -rf "${cfg_folder}/bs256"
mkdir "${cfg_folder}/bs256"
mv "${cfg_folder}/"*batchsize256* "${cfg_folder}/bs256" 
rm -rf "${cfg_folder}/bs128"
mkdir "${cfg_folder}/bs128"
mv "${cfg_folder}/"*batchsize128* "${cfg_folder}/bs128" 
rm -rf "${cfg_folder}/bs128"
mkdir "${cfg_folder}/bs64"
mv "${cfg_folder}/"*batchsize64* "${cfg_folder}/bs64"  
rm -rf "${cfg_folder}/bs128"
mkdir "${cfg_folder}/bs32"
mv "${cfg_folder}/"*batchsize32* "${cfg_folder}/bs32"

cfg_folder="cfgs/${param}_50crops256"
rm -rf "${cfg_folder}/bs128"
mkdir "${cfg_folder}/bs128"
mv "${cfg_folder}/"*batchsize128* "${cfg_folder}/bs128" 
rm -rf "${cfg_folder}/bs64"
mkdir "${cfg_folder}/bs64"
mv "${cfg_folder}/"*batchsize64* "${cfg_folder}/bs64"  
rm -rf "${cfg_folder}/bs32"
mkdir "${cfg_folder}/bs32"
mv "${cfg_folder}/"*batchsize32* "${cfg_folder}/bs32" 
rm -rf "${cfg_folder}/bs16"
mkdir "${cfg_folder}/bs16"
mv "${cfg_folder}/"*batchsize16* "${cfg_folder}/bs16"

cfg_folder="cfgs/${param}_20crops512" 
rm -rf "${cfg_folder}/bs64"
mkdir "${cfg_folder}/bs64"
mv "${cfg_folder}/"*batchsize64* "${cfg_folder}/bs64"  
rm -rf "${cfg_folder}/bs32"
mkdir "${cfg_folder}/bs32"
mv "${cfg_folder}/"*batchsize32* "${cfg_folder}/bs32" 
rm -rf "${cfg_folder}/bs16"
mkdir "${cfg_folder}/bs16"
mv "${cfg_folder}/"*batchsize16* "${cfg_folder}/bs16" 
rm -rf "${cfg_folder}/bs8"
mkdir "${cfg_folder}/bs8"
mv "${cfg_folder}/"*batchsize8* "${cfg_folder}/bs8" 

cfg_folder="cfgs/${param}_10crops1024"
rm -rf "${cfg_folder}/bs32"
mkdir "${cfg_folder}/bs32"
mv "${cfg_folder}/"*batchsize32* "${cfg_folder}/bs32" 
rm -rf "${cfg_folder}/bs16"
mkdir "${cfg_folder}/bs16"
mv "${cfg_folder}/"*batchsize16* "${cfg_folder}/bs16" 
rm -rf "${cfg_folder}/bs8"
mkdir "${cfg_folder}/bs8"
mv "${cfg_folder}/"*batchsize8* "${cfg_folder}/bs8" 
rm -rf "${cfg_folder}/bs4"
mkdir "${cfg_folder}/bs4"
mv "${cfg_folder}/"*batchsize4* "${cfg_folder}/bs4" 
